# UI Color scheme settings

# Light mode (default)
light:
  canvas:
    border:
      default: "rgba(180,180,180,255)" # Default border color from border_style.py
      normal: "#000000" # Border color in normal mode
      edit: "#FF6464" # Border color in edit mode
    background: "rgba(255,255,255,255)" # Default canvas background from border_style.py

  edge:
    line: "rgba(100,100,100,255)" # Default edge line color (was edge.normal)
    selected: "rgba(0,120,215,255)" # Selected edge color
    hover: "rgba(150,150,150,255)" # Hovered edge color
    arrow: "rgba(100,100,100,255)" # Arrow color (same as line default)
    highlighted: "#FF0000" # Highlighted edge (e.g., by knife)

  knife:
    path: "#C80000" # Knife Pass Color
    highlight: "rgba(255,165,0,200)" # Highlight color for edges to be cut

  grid:
    major_line: "rgba(64,64,64,255)" # Major grid lines (was grid.line)
    minor_line: "rgba(128,128,128,255)" # Minor grid lines
    axis_x: "rgba(230,25,25,128)" # Red for X=0 axis
    axis_y: "rgba(25,230,25,128)" # Green for Y=0 axis

  group:
    border:
      normal: "#C8C8C8" # Non-selected group border
      selected: "#6464FF" # Selected group border
    background:
      normal: "rgba(245, 245, 245, 100)" # Increased opacity for better visibility
      selected: "rgba(230, 230, 255, 120)" # Increased opacity for better visibility
    label:
      text: "#000000"
      background:
        normal: "rgba(240, 240, 240, 180)" # Label background when not selected
        selected: "rgba(240, 240, 255, 200)" # Selected label background

  node:
    fill:
      normal: "skyblue"
      selected: "#ADD8E6"
      all_for_one_selected: "#FFA07A" # Light salmon color for All-For-One mode selected nodes
      parallel_selected: "#90EE90" # Light green for Parallel connection mode
      bridge_target_highlighted: "#50FCC0" # Turquoise for target node highlighted border
      bridge_source_highlighted: "#FFD0E0" # Light pink for source node highlight
    border:
      normal: "gray"
      selected: "blue"
      all_for_one_selected: "#FF4500" # OrangeRed for All-For-One mode selected node border
      parallel_selected: "#006400" # Dark green for Parallel connection mode
      bridge_target_highlighted: "#10DDFF" # Blue with transparency for target node highlight
      bridge_source_highlighted: "#FF80A0" # Darker pink for source node highlighted border
    text: "#000000" # Node ID display text color

  mode_indicator:
    normal: "rgba(240, 240, 240, 180)"
    edit: "rgba(255, 220, 220, 180)"
    text: "#000000" # Indicator text color

  bridge: # Moved from edge section and added others
    preview: "rgba(0,191,255,180)" # Deep sky blue for preview lines
    highlight: "rgba(255,215,0,180)" # Golden for group highlights
    indicator: "rgba(50,205,50,255)" # Lime green for connection indicators
    floating_menu:
      background: "rgba(240, 240, 240, 220)" # Light gray with transparency
      text: "#000000" # Black text
      border: "#A0A0A0" # Default border color
      source_border: "#FF80A0" # Pink border for source floating menu
      target_border: "#10DDFF" # Turquoise border for target floating menu
      button:
        background: "#E0E0E0" # Light gray button
        hover: "#D0D0D0" # Slightly darker on hover
        text: "#000000" # Black text
        border: "#A0A0A0" # Medium gray border
    window:
      background: "rgba(255, 255, 255, 240)" # Almost white with transparency
      border: "#A0A0A0" # Medium gray border
      title_bar: "#E6E6FA" # Lavender color for title bar
      node_area:
        background: "#F5F5F5" # Very light gray
        connection_line: "#6495ED" # Cornflower blue
      controls:
        button:
          background: "#E0E0E0"
          hover: "#D0D0D0"
          text: "#000000"
          border: "#A0A0A0"
        counter:
          text: "#000000"
          background: "#FFFFFF"
          border: "#A0A0A0"

  selection: # Added section for selection rectangle
    # Default/Rightward selection (Blueish)
    rightward_fill: "rgba(135, 206, 235, 80)" # Light Sky Blue with more opacity
    rightward_border: "rgba(70, 130, 180, 255)" # Steel Blue
    # Leftward selection (Greenish)
    leftward_fill: "rgba(144, 238, 144, 80)" # Light Green with more opacity
    leftward_border: "rgba(60, 179, 113, 255)" # Medium Sea Green

# Dark Mode
dark:
  canvas:
    border:
      default: "rgba(100,100,100,255)"
      normal: "#FFFFFF"
      edit: "#FF8080"
    background: "rgba(40,40,40,255)"

  edge:
    line: "rgba(180,180,180,255)"
    selected: "rgba(100,180,255,255)"
    hover: "rgba(200,200,200,255)"
    arrow: "rgba(180,180,180,255)"
    highlighted: "#FF4040"

  knife:
    path: "#FF4040"
    highlight: "rgba(255,180,80,200)"

  grid:
    major_line: "rgba(100,100,100,255)"
    minor_line: "rgba(70,70,70,255)"
    axis_x: "rgba(255,50,50,128)"
    axis_y: "rgba(50,255,50,128)"

  group:
    border:
      normal: "#606060"
      selected: "#A0A0FF"
    background:
      normal: "rgba(60, 60, 60, 100)"
      selected: "rgba(70, 70, 100, 120)"
    label:
      text: "#E0E0E0"
      background:
        normal: "rgba(50, 50, 50, 180)"
        selected: "rgba(60, 60, 80, 200)"

  node:
    fill:
      normal: "#4682B4" # Steel Blue
      selected: "#5F9EA0" # Cadet Blue
      all_for_one_selected: "#CD5C5C" # Indian Red
      parallel_selected: "#3CB371" # Medium Sea Green
      bridge_target_highlighted: "#20B2AA" # Light Sea Green
      bridge_source_highlighted: "#DB7093" # Pale Violet Red
    border:
      normal: "#A0A0A0" # Gray
      selected: "#ADD8E6" # Light Blue
      all_for_one_selected: "#FF6347" # Tomato
      parallel_selected: "#98FB98" # Pale Green
      bridge_target_highlighted: "#48D1CC" # Medium Turquoise
      bridge_source_highlighted: "#FFB6C1" # Light Pink
    text: "#E0E0E0" # Light Gray text

  mode_indicator:
    normal: "rgba(60, 60, 60, 180)"
    edit: "rgba(100, 60, 60, 180)"
    text: "#E0E0E0"

  bridge:
    preview: "rgba(30,144,255,180)" # Dodger Blue
    highlight: "rgba(255,225,100,180)" # Lighter Gold
    indicator: "rgba(124,252,0,255)" # Lawn Green
    floating_menu:
      background: "rgba(50, 50, 50, 220)"
      text: "#E0E0E0"
      border: "#808080"
      source_border: "#FFB6C1" # Light Pink
      target_border: "#48D1CC" # Medium Turquoise
      button:
        background: "#606060"
        hover: "#707070"
        text: "#E0E0E0"
        border: "#808080"
    window:
      background: "rgba(45, 45, 45, 240)"
      border: "#808080"
      title_bar: "#483D8B" # Dark Slate Blue
      node_area:
        background: "#383838"
        connection_line: "#87CEEB" # Sky Blue
      controls:
        button:
          background: "#606060"
          hover: "#707070"
          text: "#E0E0E0"
          border: "#808080"
        counter:
          text: "#E0E0E0"
          background: "#505050"
          border: "#808080"

  selection: # Added section for selection rectangle
    # Default/Rightward selection (Blueish)
    rightward_fill: "rgba(70, 130, 180, 80)" # Steel Blue with transparency
    rightward_border: "rgba(135, 206, 250, 255)" # Light Sky Blue
    # Leftward selection (Greenish)
    leftward_fill: "rgba(60, 179, 113, 80)" # Medium Sea Green with transparency
    leftward_border: "rgba(144, 238, 144, 255)" # Light Green
