# UI Color scheme settings

# Light mode (default)
light:
  canvas:
    border:
      normal: "#000000"
      edit: "#FF6464"

  edge:
    normal: "#000000"
    highlighted: "#FF0000"
    bridge_preview: "rgba(100, 100, 255, 150)" # Bridge connection preview line

  knife:
    path: "#C80000" # Knife Pass Color

  grid:
    line: "#DDDDDD" # Light gray for grid lines

  group:
    border:
      normal: "#C8C8C8" # Non-selected group border
      selected: "#6464FF" # Selected group border
    background:
      normal: "rgba(245, 245, 245, 100)" # Increased opacity for better visibility
      selected: "rgba(230, 230, 255, 120)" # Increased opacity for better visibility
    label:
      text: "#000000"
      background:
        normal: "rgba(240, 240, 240, 180)" # Label background when not selected
        selected: "rgba(240, 240, 255, 200)" # Selected label background

  node:
    fill:
      normal: "skyblue"
      selected: "#ADD8E6"
      all_for_one_selected: "#FFA07A" # Light salmon color for All-For-One mode selected nodes
      parallel_selected: "#90EE90" # Light green for Parallel connection mode
      bridge_target_highlighted: "#50FCC0" # Turquoise for target node highlighted border
      bridge_source_highlighted: "#FFD0E0" # Light pink for source node highlight
    border:
      normal: "gray"
      selected: "blue"
      all_for_one_selected: "#FF4500" # OrangeRed for All-For-One mode selected node border
      parallel_selected: "#006400" # Dark green for Parallel connection mode
      bridge_target_highlighted: "#10DDFF" # Blue with transparency for target node highlight
      bridge_source_highlighted: "#FF80A0" # Darker pink for source node highlighted border
    text: "#000000" # Node ID display text color

  mode_indicator:
    normal: "rgba(240, 240, 240, 180)"
    edit: "rgba(255, 220, 220, 180)"
    text: "#000000" # Indicator text color

  bridge:
    floating_menu:
      background: "rgba(240, 240, 240, 220)" # Light gray with transparency
      text: "#000000" # Black text
      border: "#A0A0A0" # Default border color
      source_border: "#FF80A0" # Pink border for source floating menu
      target_border: "#10DDFF" # Turquoise border for target floating menu
      button:
        background: "#E0E0E0" # Light gray button
        hover: "#D0D0D0" # Slightly darker on hover
        text: "#000000" # Black text
        border: "#A0A0A0" # Medium gray border
    window:
      background: "rgba(255, 255, 255, 240)" # Almost white with transparency
      border: "#A0A0A0" # Medium gray border
      title_bar: "#E6E6FA" # Lavender color for title bar
      node_area:
        background: "#F5F5F5" # Very light gray
        connection_line: "#6495ED" # Cornflower blue
      controls:
        button:
          background: "#E0E0E0"
          hover: "#D0D0D0"
          text: "#000000"
          border: "#A0A0A0"
        counter:
          text: "#000000"
          background: "#FFFFFF"
          border: "#A0A0A0"

# Dark Mode
dark:
