# Application common constant value settings (manage modes, flags, and other hardcoded constant values)

# Node shape settings
node_shapes:
  rectangle: "rectangle"
  circle: "circle"
  default: "circle"

canvas_modes:
  normal: "normal"
  edit: "edit"

edit_submodes:
  connect: "connect" # Edge Connection Mode (Default)
  knife: "knife" # Edge Cutting Mode
  all_for_one: "all_for_one" # All-For-One Connection Mode
  parallel: "parallel" # Parallel Connection Mode
  bridge: "bridge" # Bridge Connection Mode

# Flags for deselection method
deselect_methods:
  escape: "escape" # Deselect using ESC key
  reclick: "reclick" # Click again to deselect the same node group
  background: "background" # Click on the background to deselect

  # Default settings (all enabled)
  defaults:
    escape: true
    reclick: true
    background: true

# Group label position setting
group_label_positions:
  top: "top"
  right: "right"
  bottom: "bottom"
  default: "top"

zoom:
  default: 1.0
  factor: 1200.0 # For adjusting the zoom sensitivity（delta / factor）

edge:
  draw_arrow: false # Whether to draw arrows on edges (true/false)

# User Operation Settings
interaction:
  drag_threshold: 5 # Threshold for travel distance considered drag

keyboard_shortcuts:
  edit_mode: "E" # Switching edit mode
  select_all: "Ctrl+A" # Select all node groups
  copy: "Ctrl+C" # Copy selected groups
  paste: "Ctrl+V" # Paste copied groups
  delete: "Delete" # Delete selected node group
  escape: "Escape" # Deselect
  rotate_individual: "R" # Rotate each selected element around its own center
  rotate_common_center: "Shift+R" # Rotate multiple groups around their common center point

logging:
  directory: ".log" # Log file storage directory
  filenames:
    main: "rect_graph_connector.log" # Main log file name
    error: "error.log" # Error log file name
  formats:
    log: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    date: "%Y-%m-%d %H:%M:%S"

file_output:
  directory: "./output" # Output file storage directory
  patterns:
    yaml_export: "graph_output_{date_str}.yaml" # YAML export file name pattern
    date_format: "%Y%m%d_%H%M%S" # Date format used for filenames

# Bridge connection settings
bridge_connection:
  max_selected_groups: 2 # Maximum number of groups that can be selected
  preview_line_style: "dashed" # Style for preview connection lines
  min_connections: 1 # Minimum number of connections
  max_connections: 10 # Maximum number of connections (full bipartite graph)
  highlight_positions:
    row_first: "row_first" # First node in each row
    row_last: "row_last" # Last node in each row
    col_first: "col_first" # First node in each column
    col_last: "col_last" # Last node in each column
    default: "row_first" # Default highlight position
