# Dimensions for UI Components (settings such as size, margin, and thickness)

# Hover effect settings
hover:
  opacity: 0.2 # Opacity for non-highlighted elements when hovering

canvas:
  min_height: 500
  min_zoom: 0.1
  max_zoom: 10.0
  border_width: 2 # Canvas border width

node:
  default_size: 30.0 # Default size of the node
  padding: 5 # Padding for node text
  corner_radius: 3 # Corner radius for rectangular nodes
  border_width:
    normal: 1
    selected: 2
    all_for_one_selected: 3
    parallel_selected: 3
    bridge_highlighted: 2
  node_to_node_distance: 50 # Distance between centers of adjacent nodes. Grid size is determined by this value

group:
  border_width:
    normal: 1
    selected: 2
  border_margin: 5
  label:
    fixed_width: 100
    height: 20
    text_margin: 10
    position_margin: 5

edge:
  width:
    normal: 1
    highlighted: 2
  detection_threshold: 10.0

main_window:
  initial:
    width: 800
    height: 600
  splitter:
    side_menu: 150
    canvas: 650
  layout:
    margin: 5
    spacing: 5
  control_panel:
    max_height: 50
  side_panel:
    min_width: 150

# Input widget settings
input:
  row_col_width: 50
  move_button_width: 40

# Mode Indicator Settings
mode_indicator:
  min_height: 30
  max_height: 30

# Knife Tool Settings
knife:
  path_width: 1 # Knife Pass Line Width
  highlight_width: 3.0 # Highlighted edge width when cutting

grid: # Re-added section for grid dimensions
  major_line_width: 1.0
  minor_line_width: 0.5
  # spacing is now derived from node.node_to_node_distance in GridStyle

paste:
  offset_x: 40 # Default horizontal offset for pasting groups
  offset_y: 40 # Default vertical offset for pasting groups
dialog:
  import:
    min_width: 600 # Minimum width of import dialog
    min_height: 500 # Minimum height for import dialog
    detail_height: 200 # Detailed description Minimum height of area
