# Text strings for UI components (manage text strings such as buttons, labels, titles, etc.)
# Note: The entire application translation is managed in the language/directory

main_window:
  title: "Rectangular Graph Creator"

  buttons:
    add: "Add"
    import: "Import"
    export: "Export YAML"
    reset: "Reset All"
    move_up: "↑"
    move_down: "↓"

  tooltips:
    move_up: "Move group up"
    move_down: "Move group down"

  labels:
    rows: "Rows:"
    cols: "Cols:"
    node_groups: "Node Groups"

  grid:
    snap: "Snap to Grid"

  mode:
    normal: "Mode: Normal"
    edit: "Mode: Edit"
    edit_with_target: "Mode: Edit - {group_names}" # {group_names} replaces at runtime
    edit_all_for_one: "Mode: Edit - All-For-One"
    edit_parallel: "Mode: Edit - Parallel"
    edit_bridge: "Mode: Edit - Bridge"

  dialogs:
    rename:
      title: "Rename Group"
      prompt: "Enter new group name:"
    import:
      title: "Import graph"
      filter: "YAML Files (*.yaml);;All Files (*)"

edit_menu:
  connection:
    title: "Connection"
    four_directions: "4-neighborhood"
    four_directions_tooltip: "Connect all nodes in the selected group with edges in 4 directions (up, down, left, right)."
    eight_directions: "8-neighborhood"
    eight_directions_tooltip: "Connect all nodes in the selected group with edges in 8 directions (including diagonals)."
    all_for_one: "All-For-One connection"
    all_for_one_tooltip: "Enables multiple node selection. When drawing from a selected node, identical edges extend from all selected nodes automatically."
    parallel: "Parallel connection"
    parallel_tooltip: "Enables selecting multiple nodes and drawing edges in parallel in the same direction and distance."
    bridge: "Bridge connection"
    bridge_tooltip: "Creates bipartite graph connections between two selected node groups with customizable connection patterns."
  knife:
    title: "Knife Mode (Cut Edges)"
    tooltip: "Enables knife mode to cut edges between nodes by drawing a line across them."
  delete_edges:
    title: "Delete Selected Edges"
    tooltip: "Delete the currently selected edges."
  switch_to_normal:
    title: "Switch to Normal-Mode"
    tooltip: "Switch back to normal mode for node group management."

file_handler:
  export:
    default_filename: "graph_export.yaml"
    filter: "YAML Files (*.yaml);;All Files (*)"

normal_menu:
  set_node_id:
    title: "Set Node ID Starting Index"
    prompt: "Enter the starting index for node IDs (0 or higher):"
    tooltip: "Change the starting index for node IDs in the graph."
  copy:
    title: "Copy Group"
    tooltip: "Copy the selected node group to be pasted later."
  paste:
    title: "Paste Group"
    tooltip: "Paste the previously copied node group."
  delete:
    title: "Delete Group"
    tooltip: "Delete the selected node group or nodes."
  rotate_individual:
    title: "Rotate Individual Elements"
    tooltip: "Rotate each selected group or node around its own center point by 90 degrees."
  rotate_common_center:
    title: "Rotate Around Common Center"
    tooltip: "Rotate multiple selected groups as a single unit around their common center point by 90 degrees."
  switch_to_edit:
    title: "Switch to Edit-Mode"
    tooltip: "Switch to edit mode to create and modify connections between nodes."

bridge_connection:
  window:
    title: "Bridge Connection Settings"
    source_group: "Source Group:"
    target_group: "Target Group:"
    apply: "Apply"
    cancel: "Cancel"
    close: "Close"
    connection_counts:
      source_to_target_label: "{source} → {target} connections:"
      target_to_source_label: "← {target} → {source} connections:"
      increase: "+"
      decrease: "-"
    preview_button: "Preview"
    node_selection:
      source_title: "Source Nodes"
      target_title: "Target Nodes"
      instruction: "Click nodes to toggle connection"

  floating_menu:
    title: "Edge Nodes"
    source_title: "Source Nodes"
    target_title: "Target Nodes"
    prev_button: "◀"
    next_button: "▶"
    position_label:
      row_first: "Row First"
      row_last: "Row Last"
      col_first: "Column First"
      col_last: "Column Last"
    tooltip: "Select which edge nodes to use for bridge connection"
